<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.CzEUpvL' shared service.

return $this->privates['.service_locator.CzEUpvL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'objService' => ['privates', 'App\\Service\\ExchangeRatesApiService', 'getExchangeRatesApiServiceService.php', true],
], [
    'objService' => 'App\\Service\\ExchangeRatesApiService',
]);
