<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7luXowW\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7luXowW/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7luXowW.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container7luXowW\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container7luXowW\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '7luXowW',
    'container.build_id' => '0a99948b',
    'container.build_time' => 1570183102,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7luXowW');
