<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.CqwOA2T' shared service.

return $this->privates['.service_locator.CqwOA2T'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\ExchnageRatesController::getExchangeRates' => ['privates', '.service_locator.CzEUpvL', 'get_ServiceLocator_CzEUpvLService.php', true],
    'App\\Controller\\ExchnageRatesController:getExchangeRates' => ['privates', '.service_locator.CzEUpvL', 'get_ServiceLocator_CzEUpvLService.php', true],
], [
    'App\\Controller\\ExchnageRatesController::getExchangeRates' => '?',
    'App\\Controller\\ExchnageRatesController:getExchangeRates' => '?',
]);
